#!/usr/bin/env bash
# Copy master's static assets into Hugo's static/ directory.
#
# Provenance matters here. The point of the migration is that visitors see the
# same bytes they see today, so the compiled css/style.css is copied from
# master's committed docs/ rather than recompiled from the theme's .styl.
# Recompiling would risk a different result for no benefit; the stylesheet is
# static and Hugo does not need to touch it.
#
# Must run BEFORE docs/ is replaced by a Hugo build, since docs/ is both the
# source and the destination.
#
# Everything under static/ is served verbatim by Hugo, so these paths end up
# identical to master's.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$REPO"

if [ ! -d docs/css ]; then
  echo "FAIL: docs/ has no css/ - this must run before docs/ is replaced" >&2
  exit 1
fi

echo "copying assets from docs/ to static/"
mkdir -p static

# css, js, vendor and wp-content mirror master's layout exactly
for dir in css js vendor wp-content; do
  rsync -a --exclude '._*' "docs/$dir/" "static/$dir/"
  printf '  %-12s %d files\n' "$dir" "$(find "static/$dir" -type f -not -name '._*' | wc -l | tr -d ' ')"
done

# root files that have no counterpart in source/ and so must come from docs/
#   ads.txt      - no source anywhere in the repo
#   favicon.ico  - source/ only has favicon.png; the theme has favicon.ico
for f in ads.txt favicon.ico favicon.png CNAME; do
  if [ -f "docs/$f" ]; then
    rsync -a "docs/$f" "static/$f"
    printf '  %-12s %s bytes\n' "$f" "$(wc -c < "static/$f" | tr -d ' ')"
  fi
done

echo
echo "total static files: $(find static -type f -not -name '._*' | wc -l | tr -d ' ')"
echo "master non-html files (minus the 6 generated by templates):"
echo "  $(find docs -type f -not -name 'index.html' -not -name '._*' | wc -l | tr -d ' ')"
