#!/usr/bin/env python3
"""Guard the published URL set.

Reads the paths recorded in the git index, not the ones on disk. That matters:
this repository lives on a case-insensitive volume with core.ignorecase=true, so
the filesystem cannot be trusted about letter case, while the index is exactly
what gets deployed. A build that writes docs/linux/ against a committed
docs/Linux/ is invisible to `git status` here and becomes a 404 on the
case-sensitive web server, which is precisely the bug this guards against.

Because the index is authoritative, no build is needed to check:

    python3 tools/permalinks.py            verify (exit 1 on any difference)
    python3 tools/permalinks.py --update   rewrite the manifest deliberately

Review any reported addition or removal before running --update. Adding a post
adds a URL and that is expected; losing one is a broken inbound link.
"""

import argparse
import pathlib
import subprocess
import sys

PUBLISH_DIR = "docs"
MANIFEST = pathlib.Path("permalinks.txt")

HEADER = """\
# Published permalinks. Generated by tools/permalinks.py --update.
#
# One site-relative URL per line, sorted. Any diff here is a change to a live
# address. Permalinks are permanent: if a line has to go, the old path needs a
# redirect first.
#
# Paths are site-relative, so changing the domain is not a permalink change.
# Letter case IS significant: the web server is case-sensitive even though this
# development volume is not.
#
# Regenerate with: python3 tools/permalinks.py --update
"""


def collect_from_index(publish_dir):
    """Published URLs implied by the paths staged in the git index."""
    result = subprocess.run(
        ["git", "ls-files", "-z", "--", publish_dir],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        sys.exit(f"git ls-files failed: {result.stderr.strip()}")

    prefix = f"{publish_dir}/"
    urls = set()
    for entry in result.stdout.split("\0"):
        if not entry.startswith(prefix) or not entry.endswith("/index.html"):
            continue
        directory = entry[len(prefix) : -len("/index.html")]
        urls.add("/" if not directory else f"/{directory}/")
    return urls


def read_manifest(path):
    lines = path.read_text(encoding="utf-8").splitlines()
    return {line for line in lines if line and not line.startswith("#")}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--update",
        action="store_true",
        help="rewrite permalinks.txt from the git index instead of verifying",
    )
    args = parser.parse_args()

    current = collect_from_index(PUBLISH_DIR)
    if not current:
        sys.exit(f"no {PUBLISH_DIR}/**/index.html paths in the index. Run from the repository root.")

    if args.update:
        MANIFEST.write_text(
            HEADER + "".join(f"{url}\n" for url in sorted(current)), encoding="utf-8"
        )
        print(f"wrote {len(current)} permalinks to {MANIFEST}")
        return 0

    if not MANIFEST.exists():
        sys.exit(f"{MANIFEST} not found. Run with --update to create it.")

    expected = read_manifest(MANIFEST)
    added = sorted(current - expected)
    removed = sorted(expected - current)

    if not added and not removed:
        print(f"permalinks unchanged: {len(current)} URLs")
        return 0

    for url in removed:
        print(f"  removed  {url}")
    for url in added:
        print(f"  added    {url}")
    print(f"\n{len(removed)} removed, {len(added)} added")
    print("Permalinks are permanent. Losing one breaks inbound links; confirm")
    print("each removal is intended, then run: python3 tools/permalinks.py --update")
    return 1


if __name__ == "__main__":
    sys.exit(main())