#!/usr/bin/env python3
"""Guard the published URL set.

Every page the site serves is an index.html under the publish directory, so
the permalink set is exactly the set of directory paths that hold one. This
script snapshots that set into permalinks.txt and fails when it moves.

The URLs are recorded as site-relative paths, not absolute ones, so changing
the domain does not read as a permalink change.

    python3 tools/permalinks.py            verify (exit 1 on any difference)
    python3 tools/permalinks.py --update   rewrite the manifest deliberately

Build first. A stale docs/ verifies the stale set and passes:

    hugo --cleanDestinationDir && python3 tools/permalinks.py

Review any reported addition or removal before running --update. Adding a
post adds a URL and that is expected; losing one is a broken inbound link.
"""

import argparse
import pathlib
import sys

PUBLISH_DIR = pathlib.Path("docs")
MANIFEST = pathlib.Path("permalinks.txt")

HEADER = """\
# Published permalinks. Generated by tools/permalinks.py --update.
#
# One site-relative URL per line, sorted. Any diff here is a change to a live
# address. Permalinks are permanent: if a line has to go, the old path needs a
# redirect first.
#
# Regenerate with: hugo --cleanDestinationDir && python3 tools/permalinks.py --update
"""


def is_metadata(path):
    """Skip AppleDouble sidecars, which this filesystem keeps recreating."""
    return any(part.startswith("._") or part == ".DS_Store" for part in path.parts)


def collect(publish_dir):
    urls = set()
    for index in publish_dir.rglob("index.html"):
        if is_metadata(index.relative_to(publish_dir)):
            continue
        directory = index.parent.relative_to(publish_dir).as_posix()
        urls.add("/" if directory == "." else f"/{directory}/")
    return urls


def read_manifest(path):
    lines = path.read_text(encoding="utf-8").splitlines()
    return {line for line in lines if line and not line.startswith("#")}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--update",
        action="store_true",
        help="rewrite permalinks.txt from the current build instead of verifying",
    )
    args = parser.parse_args()

    if not PUBLISH_DIR.is_dir():
        sys.exit(f"{PUBLISH_DIR}/ not found. Run from the repository root.")

    current = collect(PUBLISH_DIR)

    if args.update:
        MANIFEST.write_text(
            HEADER + "".join(f"{url}\n" for url in sorted(current)), encoding="utf-8"
        )
        print(f"wrote {len(current)} permalinks to {MANIFEST}")
        return 0

    if not MANIFEST.exists():
        sys.exit(f"{MANIFEST} not found. Run with --update to create it.")

    expected = read_manifest(MANIFEST)
    added = sorted(current - expected)
    removed = sorted(expected - current)

    if not added and not removed:
        print(f"permalinks unchanged: {len(current)} URLs")
        return 0

    for url in removed:
        print(f"  removed  {url}")
    for url in added:
        print(f"  added    {url}")
    print(f"\n{len(removed)} removed, {len(added)} added")
    print("Permalinks are permanent. Losing one breaks inbound links; confirm")
    print("each removal is intended, then run: python3 tools/permalinks.py --update")
    return 1


if __name__ == "__main__":
    sys.exit(main())